"""add table itempedido

Revision ID: 38f6f8656bf6
Revises: 5cf63173a258
Create Date: 2026-01-15 18:09:50.099076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f6f8656bf6'
down_revision: Union[str, Sequence[str], None] = '5cf63173a258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_pedido',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('num_pedido', sa.Integer(), nullable=True),
    sa.Column('produto_nome', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['num_pedido'], ['pedidos.num'], ),
    sa.ForeignKeyConstraint(['produto_nome'], ['produtos.nome'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.drop_constraint(op.f('pedidos_produtos_nomes_fkey'), 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'produtos_nomes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('produtos_nomes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pedidos_produtos_nomes_fkey'), 'pedidos', 'produtos', ['produtos_nomes'], ['nome'])
    op.drop_table('itens_pedido')
    # ### end Alembic commands ###
