"""novas colunas forma_pagamento e pago

Revision ID: 4c52a346beb8
Revises: a9836c25480c
Create Date: 2026-01-30 14:08:05.769652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c52a346beb8'
down_revision: Union[str, Sequence[str], None] = 'a9836c25480c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('forma_pagamento', sa.Text(), nullable=True))
    op.add_column('pedidos', sa.Column('pago', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'pago')
    op.drop_column('pedidos', 'forma_pagamento')
    # ### end Alembic commands ###
