"""telefone to str

Revision ID: 5cf63173a258
Revises: 71b08bb0049d
Create Date: 2026-01-14 19:01:01.315718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf63173a258'
down_revision: Union[str, Sequence[str], None] = '71b08bb0049d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('telefone', sa.Text(), nullable=False))
    op.drop_column('clientes', 'numero')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('clientes', 'telefone')
    # ### end Alembic commands ###
