"""alterando produto nome para produto num em ItemPedido

Revision ID: 97f231e8077e
Revises: d52e4dbc1148
Create Date: 2026-01-26 15:39:11.462309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f231e8077e'
down_revision: Union[str, Sequence[str], None] = 'd52e4dbc1148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedido', sa.Column('num_produto', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('itens_pedido_produto_nome_fkey'), 'itens_pedido', type_='foreignkey')
    op.create_foreign_key(None, 'itens_pedido', 'produtos', ['num_produto'], ['num'])
    op.drop_column('itens_pedido', 'produto_nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedido', sa.Column('produto_nome', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    op.create_foreign_key(op.f('itens_pedido_produto_nome_fkey'), 'itens_pedido', 'produtos', ['produto_nome'], ['nome'])
    op.drop_column('itens_pedido', 'num_produto')
    # ### end Alembic commands ###
