"""add column updated_at

Revision ID: 9893c1f1e0b8
Revises: da2d94b77af9
Create Date: 2026-02-12 11:55:01.078959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9893c1f1e0b8'
down_revision: Union[str, Sequence[str], None] = 'da2d94b77af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('pedidos', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('pedidos', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pedidos', 'updated_at')
    op.drop_column('pedidos', 'created_at')
    # ### end Alembic commands ###
