"""nova coluna valor de compra, alterando coluna valor para valor de venda (Produtos)

Revision ID: a9836c25480c
Revises: e1172ecdc2e9
Create Date: 2026-01-30 12:04:52.214171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9836c25480c'
down_revision: Union[str, Sequence[str], None] = 'e1172ecdc2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('valor_compra', sa.DECIMAL(), nullable=False))
    op.add_column('produtos', sa.Column('valor_venda', sa.DECIMAL(), nullable=False))
    op.drop_column('produtos', 'valor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('valor', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('produtos', 'valor_venda')
    op.drop_column('produtos', 'valor_compra')
    # ### end Alembic commands ###
