"""alterando cliente_nome para num_cliente em Pedido

Revision ID: c5b2fd6815c1
Revises: 97f231e8077e
Create Date: 2026-01-27 17:36:51.284056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b2fd6815c1'
down_revision: Union[str, Sequence[str], None] = '97f231e8077e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itens_pedido', 'num_pedido',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itens_pedido', 'num_produto',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('pedidos', sa.Column('num_cliente', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('pedidos_cliente_nome_fkey'), 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'clientes', ['num_cliente'], ['num'])
    op.drop_column('pedidos', 'cliente_nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('cliente_nome', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('pedidos_cliente_nome_fkey'), 'pedidos', 'clientes', ['cliente_nome'], ['nome'])
    op.drop_column('pedidos', 'num_cliente')
    op.alter_column('itens_pedido', 'num_produto',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itens_pedido', 'num_pedido',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
