"""nova tabela estoque

Revision ID: da2d94b77af9
Revises: 4c52a346beb8
Create Date: 2026-02-02 12:32:30.489645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2d94b77af9'
down_revision: Union[str, Sequence[str], None] = '4c52a346beb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('num_produto', sa.Integer(), nullable=False),
    sa.Column('ultima_atualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('estoque_atual', sa.Integer(), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['num_produto'], ['produtos.num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('num_produto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque')
    # ### end Alembic commands ###
