"""nova coluna endereco em Cliente, excluindo coluna idade e email

Revision ID: e1172ecdc2e9
Revises: c5b2fd6815c1
Create Date: 2026-01-30 11:24:47.179086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1172ecdc2e9'
down_revision: Union[str, Sequence[str], None] = 'c5b2fd6815c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('endereco', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'clientes', ['endereco'])
    op.create_unique_constraint(None, 'clientes', ['telefone'])
    op.drop_column('clientes', 'idade')
    op.drop_column('clientes', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_column('clientes', 'endereco')
    # ### end Alembic commands ###
