"""criar tabelas

Revision ID: f170ecd61627
Revises: 
Create Date: 2026-01-14 16:58:23.344547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f170ecd61627'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('num'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('produtos',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.DECIMAL(), nullable=False),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('num'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pedidos',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(), nullable=False),
    sa.Column('data', sa.TIMESTAMP(), nullable=True),
    sa.Column('produtos_nomes', sa.Text(), nullable=True),
    sa.Column('cliente_nome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_nome'], ['clientes.nome'], ),
    sa.ForeignKeyConstraint(['produtos_nomes'], ['produtos.nome'], ),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
